version: "3.9"
services:
  server:
    build: .
    ports:
      - 8080:5000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=habits_db
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: habits_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "habits_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s
